---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-pvc
  namespace: smt-local
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/code" # need to be adjusted
  storageClassName: ""