---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: horizon-worker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: horizon-worker
    spec:
      containers:
        - name: laravel
          image: ##CONTAINER_IMAGE##
          command: ["/usr/local/bin/php", "artisan", "horizon"]
          lifecycle:
            preStop:
            exec:
              command: ["/usr/local/bin/php", "artisan", "horizon:terminate"]