---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: smt-prod
  name: php-worker
spec:
  # not sure if we need schedule here as the image does most
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: php-worker
              image: smart48/smt-php-worker:latest
              command: ["/usr/local/bin/php", "artisan", "schedule:run"]