---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smt-prod
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
        - name: config
          configMap:
              name: nginx-config
              items:
              - key: config
                path: smt.conf
      containers:
        - name: laravel
          # If you don't specify a registry hostname, Kubernetes assumes that you mean the Docker public registry.
          image: smart48/smt-laravel:latest
          volumeMounts:
            - name: code
              mountPath: /code
        # Workspace for Artisan, PHP CLI
        - name: workspace
          image: smart48/smt-workspace:latest
          ports:
            - containerPort: 22
          volumeMounts:
            - name: code
              mountPath: /code
        - name: laravel-horizon
          image: smart48/smt-laravel-horizon:latest
          # not sure if we need the port and volume here
          # ports:
          #   - containerPort: 9377
          # volumeMounts:
          #   - name: code
          #     mountPath: /code
          command: ["/usr/local/bin/php", "artisan", "horizon"]
          lifecycle:
            preStop:
              exec:
                command: ["/usr/local/bin/php", "artisan", "horizon:terminate"]
        - name: nginx
          image: smart48/smt-nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /code
            - name: config
              mountPath: /etc/nginx/conf.d
      # Init Container to download code from apt_repository
      # We may not need this using port 2222 on Workspace and PHP Deployer
      initContainers:
        - name: install
          image: busybox
          volumeMounts:
            - name: code
              mountPath: /code
          command:
            - wget
            - "-O"
            - "/code/index.php"
            - https://raw.githubusercontent.com/do-community/php-kubernetes/master/index.php   
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
        
      