---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smt-prod
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: web
        tier: backend
    spec:
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
      containers:
        - name: laravel
          image: smart48/smt-laravel:latest
          volumeMounts:
            - name: code
              mountPath: /code
          initContainers:
            - name: install
              image: busybox
              volumeMounts:
                - name: code
                  mountPath: /code
              command:
                - wget
                - "-O"
                - "/code/index.php"
                - https://raw.githubusercontent.com/do-community/php-kubernetes/master/index.php   
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
        - name: nginx
          image: smart48/smt-nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /code
            - name: config
              mountPath: /etc/nginx/conf.d