apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smt-prod
  name: workspace
  labels:
    tier: backend
    app: workspace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workspace
      tier: backend
  template:
    metadata:
      labels:
        app: workspace
        tier: backend
    spec:
      volumes:
      - name: dir
        hostPath:
          path: /code
      containers:
        - name: nginx
          image: smart48/smt-nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /code