---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: smt-prod
  name: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50