---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: dir
        # path on the host https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
          hostPath:
            path: /var/www
      containers:
        - name: laravel
          image: smart48/smt-laravel:latest
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
        - name: nginx
          image: smart48/smt-nginx:latest
          ports:
            - containerPort: 80