apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: smt-local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: smart48k8.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app # refers to our app service
                port:
                  number: 8080

