apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: smt-local
spec:
  selector:
    app: workspace
  ports:
    - protocol: TCP
      port: 2222
      # targetport is the internal port where traffic is sent to
      # By default and for convenience, the targetPort is set to the same value
      # as the port field.
      targetPort: 22