apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  # hostPath is on VM so inside minikube where we added dirs 
  # and chowned them docker:docker
  hostPath:
      path: /data/code/