apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
  # hostPath is on VM so inside minikube where we added dirs 
  # and chowned them docker:docker
      path: /data/mysql/