---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code 
  namespace: smt-local
  labels:
    type: code
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi