apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-pv
  namespace: smt-local
spec:
  accessModes:
      - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    # minikube is configured to persist files stored under /data/ and a few 
    # other directories such as /var/lib/minikube in the _vm_
    path: /data