apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: smt-local
  labels:
    app: redis8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi #5 GB