apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laravel
spec:
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: asia.gcr.io/billshiun/laravel-k8s-demo
        volumeMounts:
        - name: app-secret
          mountPath: "/var/www/html/secret"
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: app-secret
        secret:
          secretName: laravel-app-secret
      imagePullSecrets:
      - name: regsecret
