apiVersion: v1
kind: Service
metadata:
  name: laravel-frontend
  namespace: default
spec:
  selector:
    app: laravel-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
