---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pvc
  namespace: smt-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: do-block-storage