---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: smt-local
  labels:
    tier: backend
spec:
  # autoscale using `kubectl autoscale deployment x --cpu-percent=50 --min=1 --max=10` instead of setting replicas
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # replicas: 2 
  selector:
    matchLabels:
      app: php
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      containers:
        - name: php
          image: php:7-fpm
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          volumeMounts:
          - name: code-storage
            mountPath: /code
        # - name: laravel-horizon
        #   image: smart48/smt-horizon:latest
        #   # not sure if we need the port and volume here
        #   imagePullPolicy: IfNotPresent
        #   ports:
        #     - containerPort: 9377
        #   volumeMounts:
        #     - name: code-storage
        #       mountPath: /code
        #   command: ["/usr/local/bin/php", "artisan", "horizon"]
        #   lifecycle:
        #     preStop:
        #       exec:
        #         command: ["/usr/local/bin/php", "artisan", "horizon:terminate"]
      # Laravel Code Download so we can run Horizon without issues 
      # and have a codebase to start with For private repo better to add 
      # code to laravel image https://codepre.com/how-to-perform-git-clone-in-kubernetes-pod-deployment.html
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
              - clone
              - --single-branch
              - --
              - https://github.com/smart48/smt-demo
              - /data
          volumeMounts:
          - mountPath: /data
            name: code-storage
      volumes:
        - name: code-storage
          persistentVolumeClaim:
            claimName: code-pv-claim

